Задание 6.7
htmlacademy-php/1886043-doingsdone-12 pull request #11
Opened 2022-09-02 12:10 UTC by Oijgen

2022-09-05 04:28 UTC, olegmifle requested changes

2022-09-05 04:28 UTC, olegmifle commented on src/add.php
> +if ($_SERVER['REQUEST_METHOD']=='POST') {
Тут, наверное, лучше проверить, что массив $_POST не пустой, ты ж потом по нему ходишь. Но думаю это не особо критично.

2022-09-05 04:28 UTC, olegmifle commented on src/add.php
> +        $fullFileName = $filePath . $fileName;
При таком подходе есть риск перезатирания файлов с одинаковым именем. Лучше или делать папку по id задачи и помещать туда файл, или делать рандомное имя. Но тоже не крит.

2022-09-05 04:28 UTC, olegmifle commented on src/functions.php
> +function addNewTask($con, $name, $projectId, $deadline, $filePath)
А типизацию где потерял? Тут и во всём файле необходимо добавить.

2022-09-05 04:28 UTC, olegmifle commented on src/functions.php
> +    return $_POST[$name] ?? "";
Двойные кавычки используй для конкатенации, для простой строки - одинарные. Тут и везде.

2022-09-05 04:28 UTC, olegmifle commented on src/functions.php
> +        $d = DateTime::createFromFormat($format, $date);
Имена переменных, функций, классов и т.д. должны быть говорящими, что бы не вчитываясь было понятно что происходит.

2022-09-05 04:28 UTC, olegmifle commented on src/functions.php
> +        elseif(strtotime($date) < strtotime(date('Y-m-d'))) {
`elseif` должно быть на одной строке с `}`, согласно psr рекомендациями. Не забывай про них - это одно из требовний при приёмке проекта.

2022-09-05 04:28 UTC, olegmifle commented on src/functions.php
> +        if (!($d && $d->format($format) == $date)) {
Не забывай про строгие сравнения. Мы используем только такие.

2022-09-05 19:58 UTC, Oijgen commented on src/add.php
> +if ($_SERVER['REQUEST_METHOD']=='POST') {
добавил

2022-09-05 22:44 UTC, Oijgen commented on src/functions.php
> +        if (!($d && $d->format($format) == $date)) {
исправил

2022-09-05 22:45 UTC, Oijgen commented on src/functions.php
> +        elseif(strtotime($date) < strtotime(date('Y-m-d'))) {
исправил

2022-09-06 06:03 UTC, Oijgen commented on src/functions.php
> +        $d = DateTime::createFromFormat($format, $date);
Исправил

2022-09-06 06:46 UTC, Oijgen commented on src/functions.php
> +function addNewTask($con, $name, $projectId, $deadline, $filePath)
исправил

2022-09-06 07:42 UTC, Oijgen commented on src/functions.php
> +    return $_POST[$name] ?? "";
исправил

2022-09-06 09:15 UTC, Oijgen commented on src/add.php
> +        $fullFileName = $filePath . $fileName;
переделал

2022-09-06 11:09 UTC, merged