Регистрация на сайте
htmlacademy-php/1886043-doingsdone-12 pull request #12
Opened 2022-09-07 21:48 UTC by Oijgen

2022-09-08 12:40 UTC, olegmifle requested changes

2022-09-08 12:40 UTC, olegmifle commented on src/account.php
> +    var_dump($mailboxIsBusy);*/
Это не нужно

2022-09-08 12:40 UTC, olegmifle commented on src/account.php
> +    $mailboxIsBusy = isMailboxBusy($usersEmail, $_POST['email']);
email ;)

2022-09-08 12:40 UTC, olegmifle commented on src/account.php
> +    $mailboxIsBusy = isMailboxBusy($usersEmail, $_POST['email']);
isEmailAvailable, например

2022-09-08 12:40 UTC, olegmifle commented on src/account.php
> +    if(!$errors['email']) {
Нужна явная проверка, так у тебя тут срабатывает приведение типов. Проверь на null например

2022-09-08 12:40 UTC, olegmifle commented on src/functions.php
> +function createNewUser(mixed $con, string $email, string  $password, string  $name)
Функция возвращает void

2022-09-08 12:40 UTC, olegmifle commented on src/functions.php
> +    return $UsersEmailQueryResult;
переменные называются с маленькой буквы
Так же типизируй что возвращает функция, а то mixed что-то непонятное

2022-09-08 12:40 UTC, olegmifle commented on src/functions.php
> +function getUsersData (mixed $con, ?int $userId): mixed
Сделай более узкую типизацию, не mixed

2022-09-08 12:40 UTC, olegmifle commented on src/functions.php
> +function getUsersData (mixed $con, ?int $userId): mixed
Тут и везде

2022-09-08 12:40 UTC, olegmifle commented on src/functions.php
> +function isMailboxBusy(mixed $usersEmail, string $newAccountEmail): bool
Сделай выборку по таблицу с юзерамо по email. Если кол-во больше нуля - почта занята. Итерировать по всем почтам - не нужно.

2022-09-08 12:40 UTC, olegmifle commented on src/functions.php
> +    if (!filter_input(INPUT_POST, $email, FILTER_VALIDATE_EMAIL)) {
А разве эта проверка срабатывает на пустой строке?

2022-09-08 19:25 UTC, Oijgen commented on src/account.php
> +    var_dump($mailboxIsBusy);*/
исправил

2022-09-08 19:54 UTC, Oijgen commented on src/account.php
> +    $mailboxIsBusy = isMailboxBusy($usersEmail, $_POST['email']);
исправил

2022-09-08 20:00 UTC, Oijgen commented on src/functions.php
> +    return $UsersEmailQueryResult;
исправил

2022-09-08 20:01 UTC, Oijgen commented on src/functions.php
> +function getUsersData (mixed $con, ?int $userId): mixed
исправил
array

2022-09-08 20:04 UTC, Oijgen commented on src/functions.php
> +    if (!filter_input(INPUT_POST, $email, FILTER_VALIDATE_EMAIL)) {
311 if (empty($_POST['email'])) {

2022-09-09 03:28 UTC, Oijgen commented on src/account.php
> +    if(!$errors['email']) {
исправил

2022-09-09 04:42 UTC, Oijgen commented on src/functions.php
> +function isMailboxBusy(mixed $usersEmail, string $newAccountEmail): bool
сделал

2022-09-09 05:00 UTC, Oijgen commented on src/functions.php
> +function createNewUser(mixed $con, string $email, string  $password, string  $name)
исправил

2022-09-12 05:58 UTC, olegmifle approved these changes

2022-09-12 05:58 UTC, merged