7.6. Вход на сайт
htmlacademy-php/1886043-doingsdone-12 pull request #13
Opened 2022-09-13 00:55 UTC by Oijgen

2022-09-14 08:22 UTC, olegmifle requested changes

2022-09-14 08:22 UTC, olegmifle commented on index.php
> +$user = getUsersData($con, $_SESSION['username']);
Сохраняй в сессию все данные о пользователе. Нет смысла ходить каждый раз. 
Для индетификатора лучше использовать id

2022-09-14 08:22 UTC, olegmifle commented on queries.sql
> +UPDATE tasks SET name = 'Сделать второе задание первого раздела' WHERE id = '9';usersusersusers
лишнее?

2022-09-14 08:22 UTC, olegmifle commented on src/add.php
> +session_start();
Лучше вынеси это в тот же init.php что бы не дёргать на каждой странице

2022-09-14 08:22 UTC, olegmifle commented on src/auth.php
> +            $errors['email'] = 'Вы ввели неверный E-mail';
Лучше не описывать так детально ошибку, это не безопасно. С помощью перебора можно получить какие email`ы уже зареганы. Ошибку лучше обезличить в духе "Неверный логин или пароль".

2022-09-14 08:22 UTC, olegmifle commented on src/functions.php
> +function checkUserPassword (mixed $con, string $email): string
Слово check намекает, что функция должна выполнять проверку. Т.е. вернуть или true, или false.

2022-09-14 08:22 UTC, olegmifle commented on src/functions.php
> +function getUsersData (mixed $con, string $email): array
Лучше вернуть как было, по id. Почта тоже уникальна в этом проекте, но id надёжнее

2022-09-14 08:22 UTC, olegmifle commented on src/functions.php
> +function checkUserProjects(mixed $con, int $userId): array
А для чего эта функция? Проверить что есть проекты?

2022-09-14 08:22 UTC, olegmifle commented on src/functions.php
> +function checkUserTasks(mixed $con, ?int $projectId): array
Тоже не понимаю что тут за проверка.

2022-09-14 10:35 UTC, Oijgen commented on src/add.php
> +session_start();
исправил

2022-09-14 10:37 UTC, Oijgen commented on src/auth.php
> +            $errors['email'] = 'Вы ввели неверный E-mail';
исправил

2022-09-14 10:45 UTC, Oijgen commented on src/functions.php
> +function checkUserProjects(mixed $con, int $userId): array
При регистрации нового пользователя у него нет ни проектов ни задач. Соответсвенно, не работает агрегированый запрос о проектах, принадлежащих данному пользователю (этот же запрос подсчитывает количество задач, привязаных к проектам). Эта функция действительно проверяет, есть ли у юзера проекты.

2022-09-14 10:45 UTC, Oijgen commented on src/functions.php
> +function checkUserTasks(mixed $con, ?int $projectId): array
Проверяет, есть ли у пользователя задачи (у новых нет)

2022-09-14 10:51 UTC, Oijgen commented on src/functions.php
> +function checkUserPassword (mixed $con, string $email): string
исправил на validate

2022-09-14 19:12 UTC, Oijgen commented on index.php
> +$user = getUsersData($con, $_SESSION['username']);
исправил

2022-09-14 19:25 UTC, Oijgen commented on src/functions.php
> +function getUsersData (mixed $con, string $email): array
Окно аутентификации - требует Емейл и пароль,  я беру из БД только эти два поля (, и если ОК, передаю управление на Index.php. В этом момент  в $_SESSION только Email, 
поэтому "function getUsersData (mixed $con, string $email): array",  после этого уже я получаю id, name

2022-09-14 19:31 UTC, Oijgen commented on queries.sql
> +UPDATE tasks SET name = 'Сделать второе задание первого раздела' WHERE id = '9';usersusersusers
исправил

2022-09-15 05:21 UTC, olegmifle commented on src/auth.php
> +        if ($checkedUserEmail===false) {
Булевы переменные обычно явно не сравнивают. Не крит, просто из практики.

2022-09-15 05:21 UTC, olegmifle commented on src/auth.php
> +                }
Вот эту логик с password_verify как раз лучше унести в validateUserPassword. Т.е. алгоритм такой
1. Достаёшь пароль по e-mail
2. Если записи в базе нет, то возвращаешь false
3. Если запись есть - сравниваешь пароли
4. Если пароли совпали - возвращаешь true, иначе false
С таким подходом, по идее, и отдельная проверка e-mail не нужна.

2022-09-15 05:21 UTC, olegmifle commented on src/functions.php
> +function getUsersData (mixed $con, string $email): array
Ты вроде добавляешь в сессию все данные о пользователе. Так что можно использовать сессию

2022-09-15 05:22 UTC, olegmifle commented on src/functions.php
> +function checkUserProjects(mixed $con, int $userId): array
Просто если это check, то в результате хочется видеть булево. Если возвращаешь массив, то тогда это уже get

2022-09-15 05:24 UTC, olegmifle commented on src/functions.php
> +function checkUserTasks(mixed $con, ?int $projectId): array
То же самое, что и выше)

2022-09-15 18:18 UTC, Oijgen commented on src/functions.php
> +function getUsersData (mixed $con, string $email): array
раньше в коде было     **$userId** = 3;  (то есть пользователь был один и фиксированый)
отсюда     $users = getUsersData (mixed $con, ?int **$userId)**: array
В задаче 7.6. процесс аутентификации  -  (ТЗ   3.3  "4. Найти в БД пользователя с переданным email.
5.Проверить, что переданный в форме пароль совпадает с сохраненным.
6.Если пользователь найден и пароли совпадают, то открыть новую сессию, в которую записать идентификатор пользователя."  - поэтому getUsersData поменялся  (?int $userId)  на  string ($email). 
В процессе аутент. используется  getUsersData, но в момент аутент. userId еще неизвестен. Я прочитал твои замечания,  и в сессию записал id, name  юзера, в лайоуте я проверяю тепер $_SESSION['userId], но при аутент. у меня нет Id, только Email. Разве что сделать еще одну функцию, которая Id достает

2022-09-15 21:11 UTC, Oijgen commented on src/functions.php
> +function checkUserProjects(mixed $con, int $userId): array
тепер возращает array и называется getUserProjects

2022-09-15 21:12 UTC, Oijgen commented on src/functions.php
> +function checkUserTasks(mixed $con, ?int $projectId): array
название не изменилось, но возвращает Bool

2022-09-15 21:18 UTC, Oijgen commented on src/auth.php
> +        if ($checkedUserEmail===false) {
теперь
(!$checkedUserEmail)

2022-09-15 22:18 UTC, Oijgen commented on src/auth.php
> +                }
переделал

2022-09-15 22:19 UTC, Oijgen commented on src/functions.php
> +function checkUserPassword (mixed $con, string $email): string
переделал

2022-09-16 12:05 UTC, merged