8.6. Полнотекстовый поиск
htmlacademy-php/1886043-doingsdone-12 pull request #14
Opened 2022-09-24 13:35 UTC by Oijgen

2022-09-26 04:57 UTC, olegmifle requested changes

2022-09-26 04:57 UTC, olegmifle commented on index.php
> +                $tasks[0]['path_to_file'] = null;
Думаю это всё не обязательно. Достаточно иметь пустой массив tasks и не пустой searchTaskName что бы понять, что был выполнен поиск и нет результатов.

2022-09-26 04:57 UTC, olegmifle commented on src/add-project.php
> +require_once 'init.php';
Ты ж уже это делал? В смысле создание проекта

2022-09-26 04:57 UTC, olegmifle commented on src/functions.php
> +    $sqlAddNewProjecQuery = 'INSERT INTO projects
Там же ещё файл должен быть, дедлайн.

2022-09-28 10:38 UTC, Oijgen commented on src/add-project.php
> +require_once 'init.php';
с заданием "8.6. Полнотекстовый поиск" немного тормозил, по-этому решил делать что-нибудь)

2022-09-28 10:43 UTC, Oijgen commented on src/functions.php
> +    $sqlAddNewProjecQuery = 'INSERT INTO projects
Я не все там сделал - сценарий, шаблон, валидация и запрос INSERT
Остальное планировал доделать в 8.7.

2022-09-28 10:51 UTC, Oijgen commented on index.php
> +                $tasks[0]['path_to_file'] = null;
Это наполнение - не для проверки
Когда я передаю пустой $tasks - разваливается шаблон main

2022-09-30 05:16 UTC, olegmifle commented on index.php
> +                $tasks[0]['path_to_file'] = null;
Так надо было бы проверок добавить в шаблон, что бы не разваливалось.

2022-09-30 05:17 UTC, olegmifle commented on src/functions.php
> +    $sqlAddNewProjecQuery = 'INSERT INTO projects
Окей. Но лучше так не делать)

2022-09-30 05:17 UTC, merged