дом. 1.13 Работа с условиями
htmlacademy-php/1886043-doingsdone-12 pull request #2
Opened 2021-11-28 14:58 UTC by Oijgen

2021-11-29 04:50 UTC, olegmifle requested changes

2021-11-29 04:50 UTC, olegmifle commented on index.php
> +                    <?php if ($show_complete_tasks == 1):?>
Нужно использовать строгое сравнение `===`. Это безопаснее.

2021-11-29 04:50 UTC, olegmifle commented on index.php
> +                        <input class="checkbox__input visually-hidden show_completed" type="checkbox" <?php if ($show_complete_tasks==1): ?> checked <?php endif ?>>
Тут нужно строгое сравнение
Можно ещё и так `<?= $show_complete_tasks === 1 ? 'checked' : ''?>`

2021-11-29 21:51 UTC, Oijgen commented on index.php
> +                    <?php if ($show_complete_tasks == 1):?>
Исправил

2021-11-29 21:51 UTC, Oijgen commented on index.php
> +                        <input class="checkbox__input visually-hidden show_completed" type="checkbox" <?php if ($show_complete_tasks==1): ?> checked <?php endif ?>>
Исправил, и использовал шорт тег

2021-11-30 04:56 UTC, olegmifle approved these changes

2021-11-30 04:56 UTC, merged