задание 2.5
htmlacademy-php/1886043-doingsdone-12 pull request #3
Opened 2021-12-05 13:05 UTC by Oijgen

2021-12-06 18:04 UTC, olegmifle requested changes

2021-12-06 18:04 UTC, olegmifle commented on index.php
> +    '1' => [
Ключи не нужно добавлять явно, если ты их не используешь для каких-то целей.

2021-12-06 18:04 UTC, olegmifle commented on index.php
> +                        <?php if (($current_task['finish_flag'])&&($show_complete_tasks ===0)):?>
Не забывай про code style - следи за отступами и т.д.

2021-12-07 16:15 UTC, Oijgen commented on index.php
> +    '1' => [
Ключи забрал

2021-12-07 18:23 UTC, Oijgen commented on index.php
> +                        <?php if (($current_task['finish_flag'])&&($show_complete_tasks ===0)):?>
просмотрел еще раз
или что то просмотрел в прошлый раз, или не до конца понимаю где лажаю
З.Ы. Может есть шпаргалка, буду благадарен

2021-12-07 20:28 UTC, Oijgen commented on index.php
> +                        <?php if (($current_task['finish_flag'])&&($show_complete_tasks ===0)):?>
Отформатировал Intellephens'oм

2021-12-08 05:21 UTC, olegmifle approved these changes

2021-12-08 05:21 UTC, merged