Задача 2.6
htmlacademy-php/1886043-doingsdone-12 pull request #4
Opened 2021-12-12 17:02 UTC by Oijgen

2021-12-13 04:37 UTC, olegmifle requested changes

2021-12-13 04:37 UTC, olegmifle commented on index.php
> +function tasks_counter($tasks_lists, $project_name) {
1. Согласно стандарту оформления кода функции и методы должны быть названы в lowerCamelCase стиле. Т.е. tasksCounter. Ещё есть смысл называть функции более декларативно что ли, типа countTasks или как-то так.
2. Это же относится и к аргументам.
3. Нет типизации, добавь плз.

2021-12-13 04:37 UTC, olegmifle commented on index.php
> +    $number_of_tasks = 0;
То же самое относится и к переменным
```suggestion
    $numberOfTasks = 0;
```

2021-12-13 04:37 UTC, olegmifle commented on index.php
> +    foreach ($tasks_lists as $task)
Ко кодстайлу скобка должна быть на той же строке.

2021-12-13 04:37 UTC, olegmifle commented on index.php
> +        if ($task['category'] === $project_name)
И тут

2021-12-17 11:46 UTC, Oijgen commented on index.php
> +function tasks_counter($tasks_lists, $project_name) {
сделал. 
("нет типизации" - если правильно понял -  отсутствие единого стиля в наименованиях,
тогда исправил)

2021-12-17 11:46 UTC, Oijgen commented on index.php
> +    $number_of_tasks = 0;
сделал

2021-12-17 11:47 UTC, Oijgen commented on index.php
> +    foreach ($tasks_lists as $task)
сделал

2021-12-17 11:47 UTC, Oijgen commented on index.php
> +        if ($task['category'] === $project_name)
сделал

2021-12-20 04:27 UTC, olegmifle requested changes

2021-12-20 04:27 UTC, olegmifle commented on index.php
> +                            <?php foreach ($projectsCategArr as $project) : ?>
`Arr` писать не нужно. То, что это массив можно отследить в 1 клик. Раньше, когда небыло ide переменные подписывали типа arrOrders или strParam, сейчас это уже рудимент

2021-12-20 04:27 UTC, olegmifle commented on index.php
> +function countTasks($tasksLists, $projectName) {
Под типизацией имею в виду казать типы аргументов и тип отдаваемого результата. В твоём случае 
```suggestion
function countTasks(array $tasksList, string $projectName): int
{
```

2021-12-20 16:28 UTC, Oijgen commented on index.php
> +                            <?php foreach ($projectsCategArr as $project) : ?>
сделал

2021-12-20 16:28 UTC, Oijgen commented on index.php
> +function countTasks($tasksLists, $projectName) {
сделал

2021-12-21 04:28 UTC, olegmifle approved these changes

2021-12-21 04:28 UTC, merged