Задание 3.6 Работаем с датой
htmlacademy-php/1886043-doingsdone-12 pull request #6
Opened 2021-12-30 22:08 UTC by Oijgen

2021-12-30 22:15 UTC, Oijgen commented
в main.php, строка 47
<tr class="tasks__item task <?= (less24hours($currentTask['finishDate']) ? 'task--important' : '') ?> <?= ($currentTask['finishFlag'] ? 'task--completed' : '') ?>">
такая конструкция работает, (не придумал как это иначе организовать)

2022-01-10 04:37 UTC, olegmifle requested changes

2022-01-10 04:37 UTC, olegmifle commented on index.php
> +function timeInterval($finishPoint) {
1. Не очень удачное название, из него не ясно что делает функция.
2. Нет указания типа аргумента, нет указания типа возвращаемого параметра.
3. Оформление не соответствует PSR-12.

2022-01-10 04:37 UTC, olegmifle commented on index.php
> +function less24hours($taskCountdown, $timeLimit = 86401) {
1. Нет указания типа аргументов, нет указания типа возвращаемого параметра.
2. Оформление не соответствует PSR-12.

2022-01-10 04:37 UTC, olegmifle commented on index.php
> +    if ($taskCountdown&&timeInterval($taskCountdown) < $timeLimit) {
1. Не понятно что содержится в $taskCountdown - что за количество?
2. Слиплись проверки, нужно отделять пробелами переменные, операторы и т.д.
3. Проверка типа `if ($taskCountdown)` не лучшая практика, если $taskCountdown не булево т.к. происходит неявное приведение типа, что может вызвать неприятные последствия.
4. Если ты хочешь вернуть булево, то возвращай булево, а не строку типа `'true'` или `'false'`. В твоём случае `'false'` никогда и не вернётся, т.е. однозначно полагаться на результат работы функции клиентскому коду нельзя.
5. Результатом проверки `if` является булево, т.е. в твоём случае можно было бы вернуть сразу 
`return $taskCountdown&&timeInterval($taskCountdown) < $timeLimit`

2022-01-10 15:30 UTC, Oijgen commented on index.php
> +function less24hours($taskCountdown, $timeLimit = 86401) {
1. указал тип аргументтов;
2. исправил оформление;

2022-01-10 15:33 UTC, Oijgen commented on index.php
> +function timeInterval($finishPoint) {
1. поменял название (на timeToFinish);
2. указал тип аргумента и тип возвращаемого парамента
3. оформление исправил;

2022-01-10 23:30 UTC, Oijgen commented on index.php
> +    if ($taskCountdown&&timeInterval($taskCountdown) < $timeLimit) {
1. $taskCountdown поменял на $Endpoint;
2. все отделил пробелами;
3. функция возвращает булевою

2022-01-11 04:30 UTC, olegmifle requested changes
В целом все замечания устранил, это хорошо. Накинул ещё замечаний

2022-01-11 04:30 UTC, olegmifle commented on index.php
> +function less24hours(string $Endpoint = NULL, int $timeLimit = 86401): bool
1. С большой буквы переменные не называют. 
2. В php не используют NULL, TRUE, FALSE в верхнем регистре, просто null, true, false.
3. Не очень понятно что такое endpoint. Если это дата окончания задачи так и пиши: taskFinishDate или типа того.
4. $timeLimit никогда не передаётся, т.е. использование его как аргумента бессмыслено.
5. Как я уже писал в прошлый раз нет смысла в условном операторе, ты можешь сразу вернуть результат сравнения как результат работы функции. Т.е. условно просто `return ($Endpoint != '') && (timeToFinish($Endpoint) < $timeLimit)`
6. Так же предпочитай строгое сравнение не строгому, вместо `==`, `!=` используй `===`, '!==` - это поможет избежать проблем с неявным приведением типов.

2022-01-12 11:56 UTC, Oijgen commented on index.php
> +function less24hours(string $Endpoint = NULL, int $timeLimit = 86401): bool
1. - 4. -- исправил
6. предпочтительно использовал строгое сравнение
5. при использовании return ($Endpoint != '') && (timeToFinish($Endpoint) < $timeLimit)  - выдавало ошибку 
что функция timeToFinish ожидает string, а получает null 
поэтому полностью переделал  и функцию less24hours, и её использование в шаблоне

2022-01-12 12:21 UTC, merged