Создание схемы БД личного проекта
htmlacademy-php/1886043-doingsdone-12 pull request #7
Opened 2022-01-13 14:17 UTC by Oijgen

2022-01-14 04:51 UTC, olegmifle requested changes

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `doingsdone`.`user` (
Каждый раз не нужно писать название БД, если после создания БД написать `USE doingsdone`

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +  CONSTRAINT `creator_id`
Выглядет не очень понятно, лучше user_id

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +  `task_creation_date` TIMESTAMP NULL,
Общепринятым названием для поля создания является created_at.

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +  `task_status` TINYINT NULL,
Такое название подталкивает к хранению какого-то статус. А тебя тут типа булво. Кажется, лучше было бы что-то в духе completed.

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +  `task_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
Не нужно писать префикс `task_` т.к. мы и так в таблице `task`

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
Нет смысла в префиксе `project_` т.к. мы уже в таблице `project`

2022-01-14 04:51 UTC, olegmifle commented on schema.sql
> +  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
Нет смысла в префиксе `user_ `т.к. мы уже в таблице `user`

2022-01-14 22:03 UTC, Oijgen commented on schema.sql
> +  CONSTRAINT `creator_id`
поменял на author

2022-01-14 22:04 UTC, Oijgen commented on schema.sql
> +  `task_creation_date` TIMESTAMP NULL,
исправил

2022-01-14 22:04 UTC, Oijgen commented on schema.sql
> +  `task_status` TINYINT NULL,
исправил

2022-01-14 22:06 UTC, Oijgen commented on schema.sql
> +  `task_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
убрал префикс
(возможно не правильно понял рекомендации
"не использовать id в качестве первичного ключа")

2022-01-14 22:06 UTC, Oijgen commented on schema.sql
> +  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
убрал префикс

2022-01-14 22:06 UTC, Oijgen commented on schema.sql
> +  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
убрал префикс

2022-01-17 04:08 UTC, olegmifle commented on schema.sql
> +  CONSTRAINT `creator_id`
user_id всё-таки было бы лучше т.к. ты связываешь с таблицей user, с полем id. Ну ок.

2022-01-17 04:08 UTC, merged