запросы
htmlacademy-php/1886043-doingsdone-12 pull request #8
Opened 2022-01-18 23:33 UTC by Oijgen

2022-01-19 06:31 UTC, olegmifle requested changes
В целом хорошо, но вот есть пара мелочей

2022-01-19 06:31 UTC, olegmifle commented on queries.sql
> +INSERT INTO tasks (name, deadline, project_id, finish_flag) VALUE ('Собеседование в IT компании', '01.07.2022', '3', FALSE);
Можно в схеме по дефолту finish_flag поставить false и не передавать его при вставке.
А ещё думаю можно finish_flag переименовать в is_finished

2022-01-19 06:31 UTC, olegmifle commented on queries.sql
> +INSERT INTO tasks (name, deadline, project_id, finish_flag) VALUE ('Собеседование в IT компании', '01.07.2022', '3', FALSE);
У тебя по ходу связи с проектом нет в БД. Иначе б ты не смог создать таски вперёд проектов

2022-01-19 16:58 UTC, Oijgen commented on queries.sql
> +INSERT INTO tasks (name, deadline, project_id, finish_flag) VALUE ('Собеседование в IT компании', '01.07.2022', '3', FALSE);
поменял на is_finished
ночью удалил внешние ключи, чтобы прогнать БД
сейчас поменял порядок таблиц - users->projects->tasks
и восстановил  ключи

2022-01-21 05:40 UTC, olegmifle requested changes
Не все замечания учтены

2022-01-21 12:59 UTC, merged