Module5 task1
htmlacademy-php/1886043-doingsdone-12 pull request #9
Opened 2022-01-28 12:20 UTC by Oijgen

2022-01-28 12:58 UTC, olegmifle requested changes

2022-01-28 12:58 UTC, olegmifle commented on index.php
> +$connection = mysqli_connect('127.0.0.1', 'root', '', 'doingsdone');
Лучше унести в конфиг. Кроме этого файла подключать придётся и в других местах.

2022-01-28 12:58 UTC, olegmifle commented on index.php
> +    mysqli_set_charset($connection, 'utf8');
Это тоже лучше сразу в конфиг.

2022-01-28 12:58 UTC, olegmifle commented on index.php
> +    $sqlProjectsQuery = 'SELECT projects.title
Раздели на функции, вынеси в functions и тут уже вызывай нужные функции. Коннект можно передавать как аргумент функции.

2022-01-28 12:58 UTC, olegmifle commented on index.php
> +function countTasks(array $innertasks, string $projectName): int
Это тоже нужно унести в functions

2022-01-28 12:58 UTC, olegmifle commented on index.php
> +                            WHERE users.id = "3"';
Вынеси как переменную, пока можно будет захардкодить при вызове функций, за то потом не придётся менять запрос

2022-02-03 06:23 UTC, freedayko requested changes

2022-02-03 06:23 UTC, freedayko commented on index.php
> +function getUsersProjects (mixed $con, $userId): mixed
Функции должны находиться в отдельном файле, например, functions.php

2022-02-03 06:23 UTC, freedayko commented on init.php
> +    $con = mysqli_connect('127.0.0.1', $login, $password, 'doingsdone');
Нет проверки что получилось открыть соединение к БД. Если не получилось код продолжит выполняться и сыпать ошибками, а необходимо отобразить пользователю что возникла внутренняя ошибка и выйти

2022-02-03 06:23 UTC, freedayko commented on init.php
> +    mysqli_set_charset($con, 'utf8');
То же самое тут, необходимо проверять что дейсвтие удалось сделать и в случае возникновения ошибки, которая критична - выходить

2022-02-03 06:23 UTC, freedayko commented on index.php
> +    $taskQueryResult = mysqli_query($con, $sqlTaskQuery);
Отсутствует проверка что удалось выполнить запрос, необходимо проверять и не выполнять дальнейший код если не получилось запрос выполнить

2022-02-03 06:23 UTC, freedayko commented on index.php
> +                          WHERE users.id = '$userId'";
Отсутствует защита от SQL инъекции (https://up.htmlacademy.ru/php/12/book/5.3)

2022-02-03 06:23 UTC, freedayko commented on init.php
> +    $con = mysqli_connect('127.0.0.1', $login, $password, 'doingsdone');
хост и имя базы данных должно быть настраиваемое тоже

2022-02-03 06:23 UTC, freedayko commented on index.php
> +$con = connection('root','');
Параметры подключения к БД лучше вынести в отдельный файл, назвать его, допустим, config.php и пусть он содержит массив настроек

2022-02-03 10:47 UTC, Oijgen commented on index.php
> +$connection = mysqli_connect('127.0.0.1', 'root', '', 'doingsdone');
исправил

2022-02-03 12:47 UTC, Oijgen commented on init.php
> +    $con = mysqli_connect('127.0.0.1', $login, $password, 'doingsdone');
исправил

2022-02-03 13:04 UTC, Oijgen commented on index.php
> +function getUsersProjects (mixed $con, $userId): mixed
исправил

2022-02-03 13:04 UTC, Oijgen commented on index.php
> +                            WHERE users.id = "3"';
исправил

2022-02-03 13:05 UTC, Oijgen commented on index.php
> +function countTasks(array $innertasks, string $projectName): int
исправил

2022-02-03 13:05 UTC, Oijgen commented on index.php
> +    $sqlProjectsQuery = 'SELECT projects.title
исправил

2022-02-03 13:06 UTC, Oijgen commented on index.php
> +    mysqli_set_charset($connection, 'utf8');
есть init  и config
перенесено в init

2022-02-03 13:06 UTC, Oijgen commented on index.php
> +$connection = mysqli_connect('127.0.0.1', 'root', '', 'doingsdone');
исправил

2022-02-03 14:30 UTC, Oijgen commented on init.php
> +    $con = mysqli_connect('127.0.0.1', $login, $password, 'doingsdone');
исправил

2022-02-03 14:31 UTC, Oijgen commented on index.php
> +    $taskQueryResult = mysqli_query($con, $sqlTaskQuery);
исправил

2022-02-03 15:29 UTC, Oijgen commented on index.php
> +                          WHERE users.id = '$userId'";
исправил

2022-02-04 21:20 UTC, merged